[package]
name = "poke"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
itertools = "0.14.0"
static_assertions = "1.1.0"
thiserror = "2.0.10"

[dev-dependencies]
pretty_assertions = "1.4.1"
