[package]
name = "poke"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bitpatterns = "0.1.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
thiserror = "2.0.10"
